controller_manager:
  ros__parameters:
    update_rate: 20
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    scara_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

scara_arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      
